### ISSUE TITLE
“You have requested package `foo', but the package provides `foo'” warning

### ISSUE THREAD

**Issue by foobar13373** [xdanaux/moderncv#1]
I'll just let TeX.Stackexchange speak her: https://tex.stackexchange.com/questions/260446

**Comment by xdanaux** [comment]
Can you please confirm this solved the issue? I just tried the proposed fix, and the warning is still there for me :(

**Comment by xdanaux** [comment]
Fixed with commit 5debb37c1f2776839b0ec5d525cd66feac5aa571.

**Comment by KommX** [comment]
When will this fix be available on CTAN?
https://www.ctan.org/pkg/moderncv

**Comment by Blaisorblade** [comment]
On TeXLive 2017, still running into this bug.

**Comment by anthony-wang** [comment]
Also seeing this issue with the latest moderncv package that is available on CTAN.

**Comment by tomaskul** [comment]
Is anyone still looking into this? And if it has actually been fixed, how do I pull the update?

EDIT: Bug still appears in 2015-08-04 package
