### ISSUE TITLE
problem with fancy and texlive in fedora 22

### ISSUE THREAD

**Issue by ghost** [xdanaux/moderncv#10]
I don't know if i must talk about that issue here or to the fedora package's owner of texlive-moderncv but when I try to use \moderncvtheme{fancy} i got that error "File `moderncvstylefancy.sty' not found."

**Comment by xdanaux** [comment]
I don't have Fedora to test, but this is likely a question of `moderncv` version. The `fancy` style was added in version 2.0.0. If the version you use is prior to that, it won't include the `fancy` style files and throw up the error you saw.
