### ISSUE TITLE
Please add tag 2.0.0 to commit f50d1cff

### ISSUE THREAD

**Issue by fcladera** [xdanaux/moderncv#11]
I am writing an Arch Linux AUR PKGBUILD to use your git repository. However, I noticed that you do not include tags in your releases.

May you add a tag to commit f50d1cff?

```
git tag -a 2.0.0 f50d1cff -m "Release 2.0.0"
git push origin 2.0.0
```

**Comment by xdanaux** [comment]
Just added back tags for every release.
