### ISSUE TITLE
Support for Xing

### ISSUE THREAD

**Issue by sfischer13** [xdanaux/moderncv#12]

**Comment by chrisma** [comment]
If you haven't used the `\extrainfo` command yet (currently there can only be a single one, it seems) you can use that to build your own Xing link in the header:

```
\extrainfo{\httplink[\faXingSquare~<XingName>]{xing.de/<xingURL>}}
```

Result:

![selection_018](https://cloud.githubusercontent.com/assets/1652117/17312743/5a5663ce-5855-11e6-9f8c-f17fbfcd22a2.png)

You can also use `\faXing` or any other [Fontawesome symbol](http://fontawesome.io/icons/).
Just make sure your template includes the Fontawesome font, e.g. `\moderncvicons{awesome}`.
In case of problems, try LuaLateX or XeLateX.

**Comment by FranklinYu** [comment]
Awesome @chrisma! This trick applies to many other sites, such as

``` latex
\extrainfo{\httplink[\faBitbucket~<username>]{bitbucket.org/<username>}}
\extrainfo{\httplink[\faGitlab~<username>]{gitlab.com/<username>}}
```
