### ISSUE TITLE
Classic Style Icons Not Match

### ISSUE THREAD

**Issue by junpengxxx** [xdanaux/moderncv#2]
Hi,

When I use classic style, the generated pdf doesn't match with the given example. The reason is that `marvosym` is used in moderncvstyleclassic.sty, not `awesome`. This leads a tricky result after I compiled template.

<img width="181" alt="screen shot 2015-08-15 at 9 25 03 pm" src="https://cloud.githubusercontent.com/assets/5428126/9291981/84a9005e-4394-11e5-88ce-71895625885a.png">

**Comment by xdanaux** [comment]
`marvosym` icons are meant to be used with the `classic` style variant by default, and that is also what the provided template shows. If you want to use the `awesome` icon set, just specify:

```
\moderncvicons{awesome}
```

in your preamble.
