### ISSUE TITLE
Double column references

### ISSUE THREAD

**Issue by nonkreon** [xdanaux/moderncv#20]
Dear Mr. Danaux,

Allow me to start by thanking you for your work on the beautiful moderncv class, I have been using it ever since I wrote my first CV when I was starting college in 2010, not to mention numerous number of people I recommended your project to. Thank you very much for all your efforts.

I have searched for a solution to my problem in the internet and especially stackexchange and could not find a solution unfortunately. My problem started after the update to version 2.0.0 I guess. 

I used to use the code provided in http://tex.stackexchange.com/a/224888 to get double column references but now even with the complete example provided there which I was able to run I get the error:

! Undefined control sequence.
<argument> \listitemmaincolumnwidth 

which is set in the recomputecvlengths command. Can you help me figure out this problem?
Thank you very much.

**Comment by aut0** [comment]
I had the same problem. I solved it by doing it like this: 

``` latex
\section{References}
  \begin{cvcolumns}
      \cvcolumn{}
      {\cvreference{Mr. Foo Bar}
      {Foo Foo}
      {Bar Bar Bar}
      {Foobarstr. 42}
      {FooFoo}
      {foo@bar.com}
      {+123456789}%
      }
      \cvcolumn{}
      {\cvreference{Mr. Foo Bar}
      {Foo Foo}
      {Bar Bar Bar}
      {Foobarstr. 42}
      {FooFoo}
      {foo@bar.com}
      {+123456789}%
      }
  \end{cvcolumns}
```

Keep the cventry command and delete the double columns

**Comment by xdanaux** [comment]
The code on TeX.SX does work - maybe you are using an old version of moderncv. Without a detailed log, it is impossible to tell.

Alternatively, use the `cvcolumns` environment as suggested by Lukas - it was designed to enable multi-columns easily. The provided template (`examples/template.tex`) illustrate how to use that environment
