### ISSUE TITLE
\cventry with month and year possible?

### ISSUE THREAD

**Issue by tobiashochguertel** [xdanaux/moderncv#3]
I describe in my CV my vocational experience with month and years, is this possible with moderncv?

![2015-08-17 22_09_25-greenshot](https://cloud.githubusercontent.com/assets/3332669/9314988/a86b4206-452c-11e5-9469-68b235c602f0.png)

**Comment by xdanaux** [comment]
Sure, you can use anything you like (years, months, or more generally, any text) as there is no input validation performed.

**Comment by tobiashochguertel** [comment]
I've got it already. Thanks for answering. Was not the best question from me. ;)
