### ISSUE TITLE
Warning about wrong package names

### ISSUE THREAD

**Issue by u-fischer** [xdanaux/moderncv#7]
moderncv loads styles with the help of \romanumeral. While `\romannumeral 1` outputs an `i` and so the file is found, the catcode of the i is different,  and so one get tons of warnings regarding the package names:

```
LaTeX Warning: You have requested package `moderncvheadi',
               but the package provides `moderncvheadi'.
```

Suggested fix (if you want to use letters instead of normal numbers in the file names):
1. Remove all the \expandafters in the definition 

```
\newcommand*{\moderncvhead}[2][]{
  \expandafter\RequirePackage\expandafter[\expandafter#1\expandafter]{\expandafter moderncvhead\romannumeral #2}}
```

There are unnecessary (and wrong as \expandafter goes behind the next token, so you are actually expanding the "o" in moderncvhead). `\RequirePackage[#1]{moderncvhead\romannumeral #2}}`  should work fine.
1. Add \romannumeral to the package declarations

```
\ProvidesPackage{moderncvhead\romannumeral 1}[2015/07/28 v2.0.0 modern curriculum vitae and letter header variant: 1]
```

**Comment by johannesbottcher** [comment]
For the sake of crossreferencing: http://tex.stackexchange.com/questions/260446/what-does-you-have-requested-package-foo-but-the-package-provides-foo-me

**Comment by FranklinYu** [comment]
Possible duplicate: #1.

**Comment by xdanaux** [comment]
This should be fixed by commit c91b6ca77c7fe422f8519a433d13db6c3c715384.

**Comment by vitaminace33** [comment]
Still there. The commit never made to final release nor CTAN.

**Comment by FranklinYu** [comment]
@vitaminace33 Development has stalled for more than 2 years; I have switched to alternatives.

**Comment by raasoft** [comment]
@FranklinYu which alternatives?

**Comment by FranklinYu** [comment]
@raasoft https://github.com/darwiin/yaac-another-awesome-cv which isn't on CTAN (yet).

**Comment by MikeDawg** [comment]
Someone interested ought to fork the project.
