### ISSUE TITLE
[FEAT] google scholar link?

### ISSUE THREAD

**Issue by xiuliren** [xdanaux/moderncv#86]
thanks for this great template! 
I find github, twitter, and linkedin, but no google scholar.
is there any option to show google scholar page?
it would be nice to have this option?

```
\social[google scholor]{name}{url link}
```

**Comment by alanlivio** [comment]
It is nice feature request.

**Comment by alanlivio** [comment]
@jingpengw, It was answer in https://github.com/moderncv/moderncv/issues/95

**Comment by xiuliren** [comment]
thank you! this version is still not updated in OverLeaf. I'll just wait for it. I have found a customized way to show it.
