### ISSUE TITLE
Add google scholar icon

### ISSUE THREAD

**Issue by alanlivio** [xdanaux/moderncv#92]
Similar as twitter or github icon/link, should be interest modercv support a Google Scholar icon/link.
As example:
```
\social[scholar]{1bEOmkUAAAAJ}
```
In such examples, it produces following icon and link:
![](https://icon2.cleanpng.com/20180413/jie/kisspng-computer-science-google-scholar-doctor-of-philosop-google-5ad094511a4771.2300740815236188971077.jpg)
http://scholar.google.com.br/citations?user=1bEOmkUAAAAJ

**Comment by 5moufl** [comment]
duplicate of https://github.com/xdanaux/moderncv/issues/86

**Comment by alanlivio** [comment]
closed on favor https://github.com/moderncv/moderncv/issues/95
